// AUTO-DERIVED from lib/validation/rules.ts — the built-in rule ids a Label
// account can override. Keep in sync via the drift test (rule emitted by the
// engine must be in BUILTIN_RULE_IDS). Do not hand-edit ids casually.

export type RuleMeta = { field: string; severities: ReadonlyArray<"critical" | "warning" | "suggestion"> };

export const RULE_META: Record<string, RuleMeta> = {
  ai_disclosure_missing: { field: "AI Disclosure", severities: ["suggestion"] },
  ai_policy_ban: { field: "AI Disclosure", severities: ["critical", "warning"] },
  ai_policy_disclose: { field: "AI Disclosure", severities: ["warning"] },
  ai_policy_open: { field: "AI Disclosure", severities: ["suggestion"] },
  ai_policy_restricted: { field: "AI Disclosure", severities: ["critical", "warning"] },
  album_empty: { field: "Album", severities: ["warning"] },
  artist_empty: { field: "Artist", severities: ["warning"] },
  artist_generic_seo: { field: "Artist", severities: ["warning"] },
  copyright_future: { field: "Copyright", severities: ["critical"] },
  copyright_old: { field: "Copyright", severities: ["warning"] },
  date_invalid: { field: "Release Date", severities: ["critical"] },
  date_missing: { field: "Release Date", severities: ["warning"] },
  date_past: { field: "Release Date", severities: ["warning"] },
  date_pitch_suboptimal: { field: "Release Date", severities: ["suggestion"] },
  date_today: { field: "Release Date", severities: ["warning"] },
  date_too_soon: { field: "Release Date", severities: ["warning"] },
  duration_farming: { field: "Duration", severities: ["suggestion"] },
  duration_missing: { field: "Duration", severities: ["suggestion"] },
  duration_too_short: { field: "Duration", severities: ["warning"] },
  explicit_mismatch: { field: "Explicit", severities: ["warning"] },
  feat_consistency: { field: "Featured Artists", severities: ["suggestion"] },
  functional_min_length: { field: "Duration", severities: ["suggestion"] },
  genre_too_broad: { field: "Genre", severities: ["suggestion"] },
  isrc_format: { field: "ISRC", severities: ["critical"] },
  isrc_is_upc: { field: "ISRC", severities: ["critical"] },
  isrc_missing: { field: "ISRC", severities: ["suggestion", "critical"] },
  iswc_format: { field: "ISWC", severities: ["warning"] },
  language_charset_mismatch: { field: "Language", severities: ["suggestion"] },
  no_copyright: { field: "Copyright", severities: ["warning"] },
  no_explicit: { field: "Explicit", severities: ["warning"] },
  no_genre: { field: "Genre", severities: ["warning"] },
  no_iswc: { field: "ISWC", severities: ["suggestion"] },
  no_label: { field: "Label", severities: ["suggestion"] },
  no_lang: { field: "Language", severities: ["suggestion"] },
  no_producer: { field: "Producers", severities: ["critical", "warning"] },
  no_splits: { field: "Splits", severities: ["suggestion"] },
  no_writers: { field: "Songwriters", severities: ["critical"] },
  splits_format: { field: "Splits", severities: ["suggestion"] },
  splits_total: { field: "Splits", severities: ["critical"] },
  title_banned_word: { field: "Title", severities: ["warning"] },
  title_brackets: { field: "Title", severities: ["warning"] },
  title_caps: { field: "Title", severities: ["warning"] },
  title_double_space: { field: "Title", severities: ["suggestion"] },
  title_empty: { field: "Title", severities: ["critical"] },
  title_feat_in_title: { field: "Title", severities: ["warning"] },
  title_keyword_stuffing: { field: "Title", severities: ["warning"] },
  title_lowercase: { field: "Title", severities: ["warning"] },
  title_parens: { field: "Title", severities: ["critical"] },
  title_special_chars: { field: "Title", severities: ["warning"] },
  title_store_name: { field: "Title", severities: ["warning"] },
  title_titlecase: { field: "Title", severities: ["suggestion"] },
  title_unicode_decorative: { field: "Title", severities: ["warning"] },
  title_url: { field: "Title", severities: ["critical"] },
  title_version_format: { field: "Title", severities: ["warning"] },
  title_ws: { field: "Title", severities: ["warning"] },
  upc_checkdigit: { field: "UPC", severities: ["critical"] },
  upc_format: { field: "UPC", severities: ["critical"] },
  upc_is_isrc: { field: "UPC", severities: ["critical"] },
  upc_missing: { field: "UPC", severities: ["suggestion", "warning"] },
  writer_legal_name: { field: "Songwriters", severities: ["suggestion"] },
};

export const BUILTIN_RULE_IDS: ReadonlySet<string> = new Set(Object.keys(RULE_META));
